version: "3.9"
services:
    db-mysql:
        image: "mysql:5.6"
        container_name: db-mysql
        environment:
          - MYSQL_ROOT_PASSWORD=aziz123
        ports:
          - "3307:3306"
        restart: unless-stopped
    Validation_DevOps:
      container_name: Validation_DevOps
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8089:8089"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/Devops?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
        - spring.datasource.username=root
        - spring.datasource.password=aziz123
      image: station-ski
      command: mvn test
      restart: unless-stopped
    
