# Utilisez l'image de base openjdk:8
FROM openjdk:8

# Exposez le port 8090
EXPOSE 8090

# Copiez le fichier JAR de votre application dans le conteneur
COPY target/gestion-station-ski-1.0.jar gestion-station-ski-1.0.jar

# Commande d'entrée pour démarrer votre application
CMD ["java", "-jar", "gestion-station-ski-1.0.jar"]
