version: "3.9"

services:
  Validation_DevOps:
    container_name: Validation_DevOps
    build: Validation_DevOps
    ports:
      - "8"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:ski;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    image: "ski"
    command: mvn test
    restart: unless-stopped