version: "3.7"
services:
    mysqldb:
      container_name: mysqldb
      image: mysql:latest
      restart: unless-stopped
      ports:
        - 3306:3306
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=stationSki

      volumes:
        - db:/var/lib/mysqldb

    ski_app:
        image: chamseddine777/ski-image:latest
        container_name: ski_app
        restart: unless-stopped
        ports:
          - 8089:8089

        environment:
         - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?autoReconnect=true&useSSL=false
         - spring.datasource.username=root
         - spring.datasource.password=

        depends_on:
         - mysqldb
        stdin_open: true
        tty: true
        volumes:
        - .m2:/root/.m2
volumes:
      db: